stages:

- name: Build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |
        export ALIAS_yaml=$ALIAS_account_main
        mkdir -p config
        echo "$ALIAS_yaml" > config.yaml
    envFrom:
    - sourceName: pmas-connector-config
      sourceKey: main
      targetKey: ALIAS_account_main
  - publishImageConfig:
      buildContext: .
      tag: pmas-connector:${CICD_GIT_COMMIT}
      dockerfilePath: ./Dockerfile.test-config
 
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
 
branch:
  include: [main]
timeout: 60
notification: {}